language: node_js
sudo: false
node_js:
  - "10"
before_install:
  - cd test/fixtures/template
  - npm install
  - cd -
before_script:
  - npm link
  - export NODE_PATH="$(npm prefix -g)/lib/node_modules"
